### ISSUE TITLE
Message type 24 (Class B static data) does not detect and correctly decode part B

### ISSUE THREAD

**Issue by astuder** [wpietri/simpleais#7]
Message type 24 comes in two variants, called "part A" and "part B". simpleais always returns both sets of fields.

Example message: `!AIVDM,1,1,,B,H5NhCmTN7B=400500000001P0004,0*56`

Decoded by simpleais:
```
type 24
repeat 0
mmsi 367793110
partno 1
shipname G!4#Q@@AP@@@@@@@X
ignored-160 4
shiptype Fishing
vendorid GRM
model 1
serial 5
callsign
to_bow 12
to_stern 0
to_port 0
to_starboard 0
mothership_mmsi 25165824
ignored-162 4
text None
```

Correct decoding (via [Maritec](https://www.maritec.co.za/tools/aisvdmvdodecoding)):
```
type 24
repeat 0
mmsi 367793110
part_no 1
type fishing
vendorid GRMD@@E
callsign @@@@@@@
to_bow 12
to_stern 0
to_port 0
to_starboard 0
spare 4
```

The output for shipname may be uninitialized memory, at one occasion I got `C: DRIVE` - Edit: Never mind, there's a ship with that name :)

This type may require some custom handling as the documentation for AIVDM merged both definitions into the same table:
https://gpsd.gitlab.io/gpsd/AIVDM.html#_type_24_static_data_report

**Comment by wpietri** [comment]
Thanks for mentioning this. Just to understand the priority, is this something you actively need? Or is it more a desire to have everything correct?

**Comment by astuder** [comment]
I can work around it with a few lines of Python code.

But for the common msg type 24 (sent by pleasure boats), it's a bit jarring to see the invalid names when using aist. Though that might be an oversight in aist as I now see that you already check for partno in there.

**Comment by astuder** [comment]
I implemented a fix in https://github.com/astuder/simpleais/tree/type24 

It introduces the concept of subtypes, where the value of one field controls the decoding of other fields. Each unique subtype creates a trimmed instance of MessageDecoder, which is requested by the constructor of Sentence if applicable.

This fixes the issue with overlapping field definitions when decoding type 22 (channel management) and type 24 (static data report):

```
Sentence 1:
          text: !AIVDM,1,1,,B,H5Nv6n058TDj0tJ1HT=@u8T4000,2*3E
        length: 160
          type: 24
        repeat: 0
          mmsi: 368019160
        partno: 0
      shipname: ARIEL OF VICTORIA
   ignored-160: -

Sentence 2:
          text: !AIVDM,1,1,,B,H5Nv6n4T0000000G4:pojh1h5130,0*62
        length: 168
          type: 24
        repeat: 0
          mmsi: 368019160
        partno: 1
      shiptype: Sailing
      vendorid: 
         model: 0
        serial: 0
      callsign: WDJ8720
        to_bow: 14
      to_stern: 5
       to_port: 1
  to_starboard: 3
  mothership_mmsi: 29380675
   ignored-162: 0
```

mothership_mmsi still is a problem as its handling requires more complex rules depending on mmsi field. I haven't seen this in use in the wild yet. 

This fix also improves support for dest_mmsi in type 25/26 (single/multiple slot binary message), but those messages probably still won't return the data field. Though, according to AIVDM documentation, these message types haven't been seen in the wild.

This branch also fixes warnings about escaping of backslashes in aivdm_translate.py
